spawn-on-join: default
newbies:
  spawnpoint: newbie
spawns:
  global:
    location:
      ==: org.bukkit.Location
      world: world
      x: 0.5
      y: 64.0
      z: -202.5
      pitch: -0.9
      yaw: 90.3
